// SOCKET EVENT & NOTIFICATION TYPE CONSTANTS (MATCHING BACKEND 1:1)

export const SOCKET_EVENT_CONSTANT = {
	NEW_NOTIFICATION: 'NEW_NOTIFICATION',
	NOTIFICATION: 'NOTIFICATION',
	KYC_REQUEST: {
		SUBMITTED: 'KYC_REQUEST_SUBMITTED',
		APPROVED: 'KYC_REQUEST_APPROVED',
		REJECTED: 'KYC_REQUEST_REJECTED',
	},
	API_KEY_REQUEST: {
		SUBMITTED: 'API_KEY_REQUEST_SUBMITTED',
		APPROVED: 'API_KEY_REQUEST_APPROVED',
		REJECTED: 'API_KEY_REQUEST_REJECTED',
	},
} as const;

export const NOTIFICATION_TYPE_CONSTANT = SOCKET_EVENT_CONSTANT;

export type TSocketEvent = (typeof SOCKET_EVENT_CONSTANT)[keyof typeof SOCKET_EVENT_CONSTANT];

export default SOCKET_EVENT_CONSTANT;
